[package]
name = "screentearctl"
version = "0.1.0"
edition = "2021"

[build-dependencies]
clap = { version = "4.0.11", features = ["derive"] }
clap_complete = "4.0.2"
regex = "1.6.0"

[dependencies]
clap = { version = "4.0.11", features = ["derive"] }
clap_complete = "4.0.2"
regex = "1.6.0"

